# JDBC
quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=17
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${QUARKUS_HTTP_CORS_ORIGIN}
quarkus.http.cors.methods=GET,POST,PATCH,DELETE

# Test
%test.quarkus.hibernate-orm.database.version-check.enabled=false
%test.quarkus.hibernate-orm.sql-load-script=no-file
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
%test.quarkus.hibernate-orm.database.generation=drop-and-create