# JDBC
quarkus.datasource.db-kind = postgresql
quarkus.datasource.db-version = 17
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}

# Hibernate
quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.database.start-offline=true
quarkus.hibernate-orm.sql-load-script=import.sql